### ISSUE TITLE
Invalid password found on Parrot Linux

### ISSUE THREAD

**Issue by austinbentlee** [r3nt0n/keepass4brute#5]
Looks like the latest commit broke this script on Parrot Linux.

The root cause appears to be that keepassxc-cli doesn't return a status code on failure to open the database. I know that previously you had checked the database error text, which unfortunately didn't work on non-English languages. 

![image](https://github.com/r3nt0n/keepass4brute/assets/51935104/bad137cb-da01-4e8c-9177-42ede11924ec)

Might be worth complaining to a package maintainer or the repo for keepassxc-cli, but wanted to make sure you were aware, maybe you have an easy fix.

![image](https://github.com/r3nt0n/keepass4brute/assets/51935104/de89d87f-3314-431e-b8b3-0968c9917edc)

**Comment by r3nt0n** [comment]
Hello! Thanks for letting me know :)

I tried this on 2.7.4 and it was returning different codes as expected, maybe they already fixed it? I'm not a Parrot user, as far as I know is built on top on Debian, could you try upgrading your keepassxc package to the latest available version? It should be 2.7.4. If not, maybe worth to ask Parrot mantainers to upgrade their repositories to newest versions (2.6.2 was released on 2020).
